Default: &defaults
  database: kamome.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: kamome_test.sqlite3
  <<: *defaults

Staging:
  database: kamome_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: kamome_production.sqlite3
  poolsize: 100
  <<: *defaults
